// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSlight.Data.Context;

namespace OSlight.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210113012726_InitApp")]
    partial class InitApp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OSlight.Business.Models.AbrirOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("NomeReclamante")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumeroPoste")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AbrirOS");
                });

            modelBuilder.Entity("OSlight.Business.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AbrirOSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AbrirOSId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("OSlight.Business.Models.FecharOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AbrirOSId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("AbrirOSId")
                        .IsUnique();

                    b.ToTable("fecharOs");
                });

            modelBuilder.Entity("OSlight.Business.Models.Endereco", b =>
                {
                    b.HasOne("OSlight.Business.Models.AbrirOS", "AbrirOS")
                        .WithOne("Endereco")
                        .HasForeignKey("OSlight.Business.Models.Endereco", "AbrirOSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbrirOS");
                });

            modelBuilder.Entity("OSlight.Business.Models.FecharOS", b =>
                {
                    b.HasOne("OSlight.Business.Models.AbrirOS", "AbrirOS")
                        .WithOne("FecharOS")
                        .HasForeignKey("OSlight.Business.Models.FecharOS", "AbrirOSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbrirOS");
                });

            modelBuilder.Entity("OSlight.Business.Models.AbrirOS", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("FecharOS");
                });
#pragma warning restore 612, 618
        }
    }
}
